# Generated by Django 5.1.5 on 2025-02-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='fallback.png', upload_to='carousel/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
